"""
Setup script for ftrack_hou_utils package.
"""
import os
from setuptools import setup, find_packages

# Read version from __init__.py
with open(os.path.join("ftrack_hou_utils", "__init__.py"), "r") as f:
    for line in f:
        if line.startswith("__version__"):
            version = line.split("=")[1].strip().strip('"').strip("'")
            break

# Read README.md
with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

# Dependencies
install_requires = [
    "ftrack-python-api>=2.0.0",
    "pyyaml>=6.0.1",
    "typing-extensions>=4.8.0",
    "pathlib>=1.0.1",
    "colorama>=0.4.6",
    "rich>=13.6.0",
    "tqdm>=4.66.1",
    "requests>=2.31.0",
    "urllib3>=2.0.7",
    "certifi>=2023.7.22",
    "charset-normalizer>=3.3.0",
    "idna>=3.4",
    "six>=1.16.0",
    "python-dateutil>=2.8.2",
    "arrow>=1.3.0",
    "types-PyYAML>=6.0.12.12",
    "types-requests>=2.31.0.10",
    "types-urllib3>=1.26.25.14",
    "types-python-dateutil>=2.8.19.14",
]

test_requires = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",
    "pytest-timeout>=2.2.0",
    "pytest-xdist>=3.3.1",
    "pytest-randomly>=3.15.0",
    "pytest-repeat>=0.9.3",
    "pytest-rerunfailures>=12.0",
    "pytest-sugar>=0.9.7",
    "pytest-html>=4.1.1",
    "pytest-metadata>=3.0.0",
    "pytest-reportlog>=0.3.0",
    "pytest-json-report>=1.5.0",
    "pytest-benchmark>=4.0.0",
    "pytest-profiling>=1.7.0",
    "pytest-clarity>=1.0.1",
    "pytest-picked>=0.5.0",
    "pytest-instafail>=0.5.0",
    "pytest-ordering>=0.6",
    "pytest-env>=1.1.1",
    "pytest-custom-exit-code>=0.3.0",
    "pytest-check>=2.2.2",
    "pytest-asyncio>=0.21.1",
    "pytest-timeout>=2.2.0",
    "pytest-freezegun>=0.4.2",
    "pytest-recording>=0.13.1",
    "pytest-vcr>=1.0.2",
    "pytest-responses>=0.5.1",
    "pytest-httpserver>=1.0.8",
    "pytest-localserver>=0.8.1",
    "pytest-socket>=0.6.0",
    "pytest-docker>=2.0.1",
    "pytest-docker-compose>=3.2.1",
    "pytest-services>=2.2.1",
    "pytest-selenium>=4.0.2",
    "pytest-base-url>=2.0.0",
    "pytest-variables>=3.0.0",
    "pytest-html-reporter>=0.2.9",
    "pytest-parallel>=0.1.1",
    "pytest-xprocess>=0.23.0",
    "pytest-subprocess>=1.5.0",
    "pytest-mock-resources>=2.9.2",
    "pytest-lazy-fixture>=0.6.3",
    "pytest-regressions>=2.4.3",
    "pytest-snapshot>=0.9.0",
    "pytest-watch>=4.2.0",
    "pytest-testmon>=2.0.13",
    "pytest-test-groups>=1.0.3",
    "pytest-test-utils>=0.0.3",
    "pytest-test-cases>=3.4.3",
    "pytest-test-context>=0.2.0",
    "pytest-test-selector>=0.2.0",
    "pytest-test-this>=1.1.3",
    "pytest-test-name>=0.2.0",
]

dev_requires = [
    "black>=23.10.1",
    "isort>=5.12.0",
    "flake8>=6.1.0",
    "mypy>=1.6.1",
    "pylint>=3.0.2",
    "bandit>=1.7.5",
    "safety>=2.3.5",
    "pre-commit>=3.5.0",
    "commitizen>=3.12.0",
    "bump2version>=1.0.1",
    "twine>=4.0.2",
    "build>=1.0.3",
    "pip-tools>=7.3.0",
    "pipdeptree>=2.13.1",
    "pip-audit>=2.6.1",
    "pip-review>=1.3.0",
    "pip-licenses>=4.3.3",
    "pip-requirements-parser>=32.0.1",
    "pip-compile-multi>=2.6.3",
    "pip-tools-multi>=0.8.0",
    "pip-upgrader>=1.4.15",
    "pip-check>=2.7.4",
    "pip-autoremove>=0.10.0",
    "pip-chill>=1.0.3",
    "pip-outdated>=0.6.0",
    "pip-check-reqs>=2.5.1",
    "pip-conflict-checker>=0.6.0",
    "pip-tools-secure>=0.5.0",
    "pip-audit>=2.6.1",
    "pip-review>=1.3.0",
    "pip-licenses>=4.3.3",
    "pip-requirements-parser>=32.0.1",
    "pip-compile-multi>=2.6.3",
    "pip-tools-multi>=0.8.0",
    "pip-upgrader>=1.4.15",
    "pip-check>=2.7.4",
    "pip-autoremove>=0.10.0",
    "pip-chill>=1.0.3",
    "pip-outdated>=0.6.0",
    "pip-check-reqs>=2.5.1",
    "pip-conflict-checker>=0.6.0",
    "pip-tools-secure>=0.5.0",
]

docs_requires = [
    "sphinx>=7.2.6",
    "sphinx-rtd-theme>=1.3.0",
    "sphinx-autodoc-typehints>=1.24.0",
    "sphinx-autoapi>=3.0.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.5.0",
    "sphinx-inline-tabs>=2023.4.21",
    "sphinx-issues>=3.0.1",
    "sphinx-notfound-page>=1.0.0",
    "sphinx-prompt>=1.8.0",
    "sphinx-tabs>=3.4.1",
    "sphinx-togglebutton>=0.3.2",
    "sphinx-toolbox>=3.5.0",
    "sphinx-version-warning>=1.1.2",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-click>=5.0.1",
    "sphinx-contributors>=0.2.7",
    "sphinx-favicon>=1.0.1",
    "sphinx-gallery>=0.14.0",
    "sphinx-git>=11.0.0",
    "sphinx-hoverxref>=1.3.0",
    "sphinx-immaterial>=0.11.7",
    "sphinx-inline-tabs>=2023.4.21",
    "sphinx-issues>=3.0.1",
    "sphinx-last-updated-by-git>=0.3.6",
    "sphinx-markdown-builder>=0.6.5",
    "sphinx-material>=0.0.36",
    "sphinx-multiversion>=0.2.4",
    "sphinx-panels>=0.6.0",
    "sphinx-pypi-upload>=0.2.1",
    "sphinx-readable-theme>=1.3.0",
    "sphinx-sitemap>=2.5.1",
    "sphinx-theme>=1.0",
    "sphinx-thebe>=0.2.1",
    "sphinx-theme-pd>=0.0.2",
    "sphinx-typlog-theme>=0.8.0",
    "sphinx-wagtail-theme>=5.1.0",
    "sphinx-websequencediagrams>=0.1.0",
    "sphinx-yaml>=0.3.0",
    "sphinx-zephyr-theme>=1.0.0",
]

setup(
    name="ftrack_hou_utils",
    version=version,
    description="Utilities for Ftrack integration with Houdini",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/ftrack_hou_utils",
    packages=find_packages(exclude=["tests*"]),
    package_data={
        "ftrack_hou_utils": [
            "templates/*.yaml",
            "templates/*.json",
            "templates/*.yml",
            "templates/*.jsonc",
            "templates/*.template",
            "templates/*.tpl",
            "templates/*.j2",
            "templates/*.jinja",
            "templates/*.jinja2",
            "templates/*.html",
            "templates/*.xml",
            "templates/*.txt",
            "templates/*.md",
            "templates/*.rst",
            "templates/*.ini",
            "templates/*.cfg",
            "templates/*.conf",
            "templates/*.config",
            "templates/*.properties",
            "templates/*.env",
            "templates/*.toml",
            "templates/*.yaml.example",
            "templates/*.json.example",
            "templates/*.yml.example",
            "templates/*.jsonc.example",
            "templates/*.template.example",
            "templates/*.tpl.example",
            "templates/*.j2.example",
            "templates/*.jinja.example",
            "templates/*.jinja2.example",
            "templates/*.html.example",
            "templates/*.xml.example",
            "templates/*.txt.example",
            "templates/*.md.example",
            "templates/*.rst.example",
            "templates/*.ini.example",
            "templates/*.cfg.example",
            "templates/*.conf.example",
            "templates/*.config.example",
            "templates/*.properties.example",
            "templates/*.env.example",
            "templates/*.toml.example",
        ],
    },
    install_requires=install_requires,
    extras_require={
        "test": test_requires,
        "dev": dev_requires + test_requires,
        "docs": docs_requires,
        "all": test_requires + dev_requires + docs_requires,
    },
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Multimedia :: Graphics :: 3D Modeling",
        "Topic :: Multimedia :: Graphics :: 3D Rendering",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Version Control :: Git",
        "Topic :: System :: Software Distribution",
        "Topic :: System :: Systems Administration",
        "Topic :: Utilities",
        "Typing :: Typed",
    ],
    keywords=[
        "houdini",
        "ftrack",
        "pipeline",
        "asset management",
        "production tracking",
        "vfx",
        "animation",
        "3d",
        "cg",
        "templates",
        "automation",
        "utilities",
        "tools",
        "framework",
        "library",
        "api",
        "integration",
        "plugin",
        "extension",
        "addon",
        "module",
        "package",
        "development",
        "software",
        "application",
        "system",
        "platform",
        "solution",
        "service",
        "component",
        "infrastructure",
        "architecture",
        "design",
        "pattern",
        "practice",
        "methodology",
        "standard",
        "specification",
        "reference",
        "guide",
        "documentation",
    ],
    project_urls={
        "Documentation": "https://ftrack-hou-utils.readthedocs.io/",
        "Source": "https://github.com/yourusername/ftrack_hou_utils",
        "Tracker": "https://github.com/yourusername/ftrack_hou_utils/issues",
        "Changelog": "https://github.com/yourusername/ftrack_hou_utils/blob/main/CHANGELOG.md",
    },
    entry_points={
        "console_scripts": [
            "ftrack-hou-utils=ftrack_hou_utils.cli:main",
        ],
    },
    zip_safe=False,
) 